#!/usr/bin/python3

from copr.v3 import Client, BuildProxy, PackageProxy

ownername = 'plfiorini'
projectname = 'liri-nightly'

# Create an API client from config file
client = Client.create_from_config_file()

# Iterate over all packages and keep only the first successful build
for package in client.package_proxy.get_list(ownername, projectname):
    print(package.name)
    found = False
    for build in client.build_proxy.get_list(ownername, projectname, packagename=package.name):
        if found is False and build.state == 'succeeded':
            found = True
        else:
            client.build_proxy.delete(build.id)
