#!/bin/bash

outdir=$1
srcpkgdir=$2

if [ -z "$outdir" -o -z "$spec" ]; then
    echo "Usage: $0 [outdir] [spec_path]"
    exit 1
fi

pkgname=`basename $srcpkgdir -git`

if ! test `command -v git`; then
    dnf -y install git
fi

if ! test `command -v spectool`; then
    dnf -y install rpmdevtools
fi

source ${srcpkgdir}/.sourceinfo

pushd /tmp >/dev/null
git clone --depth 1 -b $gitbranch $giturl $pkgname
cd $pkgname
_gitdate=$(date -d @$(git log -1 --format="%at") +%Y%m%d)
_githash=$(git log -1 --format="%H")
popd >/dev/null
rm -rf /tmp/$pkgname

[ -z "$_gitdate" -o -z "$_githash" ] && exit 1

sed -e "s,@DATE@,${_gitdate},g" -e "s,@HASH@,${_githash},g" ${srcpkgdir}/${pkgname}.spec > ${outdir}/${pkgname}.spec
pushd $outdir >/dev/null
spectool -g ${pkgname}.spec
srpm=$(LC_ALL=C rpmbuild --define "_sourcedir ${outdir}" --define "_specdir ${outdir}" --define "_builddir ${outdir}" \
    --define "_srcrpmdir ${outdir}" --define "_rpmdir ${outdir}" --define "_buildrootdir ${outdir}/.build" \
    -bs ${pkgname}.spec | sed -e 's,Wrote: ,,g')
popd >/dev/null
if [ -z "$srpm" ]; then
	exit 1
fi
cp $srpm .

echo $(basename $srpm)
