#!/bin/bash

pkgname=$1

if [ -z "$pkgname" ]; then
    echo "Usage: $0 [package name]"
    exit 1
fi

srcpkgdir=${pkgname}-git
srcdir=$(pwd)

rm -f *.src.rpm

source ${srcpkgdir}/.sourceinfo

pushd /tmp >/dev/null
git clone --depth 1 -b $gitbranch $giturl $pkgname
cd $pkgname
_gitdate=$(date -d @$(git log -1 --format="%at") +%Y%m%d)
_githash=$(git log -1 --format="%H")
popd >/dev/null
rm -rf /tmp/$pkgname

[ -z "$_gitdate" -o -z "$_githash" ] && exit 1

srpmdir=/tmp/${pkgname}-srpm
mkdir -p $srpmdir
sed -e "s,@DATE@,${_gitdate},g" -e "s,@HASH@,${_githash},g" ${srcpkgdir}/${pkgname}.spec > ${srpmdir}/${pkgname}.spec
pushd $srpmdir >/dev/null
spectool -g ${pkgname}.spec
srpm=$(LC_ALL=C rpmbuild --define "_sourcedir ${srpmdir}" --define "_specdir ${srpmdir}" --define "_builddir ${srpmdir}" \
    --define "_srcrpmdir ${srpmdir}" --define "_rpmdir ${srpmdir}" --define "_buildrootdir ${srpmdir}/.build" \
    -bs ${pkgname}.spec | sed -e 's,Wrote: ,,g')
popd >/dev/null
if [ -z "$srpm" ]; then
	rm -rf $srpmdir
	exit 1
fi
cp $srpm .
rm -rf $srpmdir

echo ${srcdir}/$(basename $srpm)
