#!/bin/bash

set -ex

outdir=$1
spec=$2

if [ -z "$outdir" -o -z "$spec" ]; then
    echo "Usage: $0 [outdir] [spec_path]"
    exit 1
fi

if ! test `command -v git`; then
    dnf -y install git
fi

if ! test `command -v spectool`; then
    dnf -y install rpmdevtools
fi

pkgdir=$(realpath `dirname $spec`)
pkgname=$(basename $spec .spec)

source ${pkgdir}/.sourceinfo

####
pushd /tmp >/dev/null

git clone --depth 1 -b $gitbranch $giturl $pkgname
cd $pkgname
_gitdate=$(date -d @$(git log -1 --format="%at") +%Y%m%d)
_githash=$(git log -1 --format="%H")

if [ -z "$_gitdate" -o -z "$_githash" ]; then
    echo "Failed to determine git revision"
    exit 1
fi

qbs_filename=$(echo $pkgname | sed -e 's,^liri-,,g' -e 's,^qt5-,,g').qbs
version=$(cat $qbs_filename | grep 'property string version' | perl -p -e 's@.+"([\d.]+)"$@$1@g')
if [ -z "$version" ]; then
    echo "Failed to determine package version"
    exit 1
fi
curl "https://raw.githubusercontent.com/fsaintjacques/semver-tool/master/src/semver" >/tmp/semver
chmod 755 /tmp/semver
newversion=$(/tmp/semver bump minor $version)

popd >/dev/null
rm -rf /tmp/$pkgname
####

sed -e "s,@VERSION@,${newversion},g" -e "s,@DATE@,${_gitdate},g" -e "s,@HASH@,${_githash},g" ${pkgdir}/${pkgname}.spec > ${outdir}/${pkgname}.spec
pushd $outdir >/dev/null
spectool -g ${pkgname}.spec
LC_ALL=C rpmbuild --define "_sourcedir ${outdir}" --define "_specdir ${outdir}" --define "_builddir ${outdir}" \
    --define "_srcrpmdir ${outdir}" --define "_rpmdir ${outdir}" --define "_buildrootdir ${outdir}/.build" \
    -bs ${pkgname}.spec
popd >/dev/null

rm -rf ${outdir}/.build
